global:
  scrape_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: grafana
    scrape_interval: 1m
    static_configs:
      - targets:
        - grafana:3000

  - job_name: node
    static_configs:
      - targets: 
        - 'node_exporter:9100'
  
  - job_name: traefik
    static_configs:
      - targets: 
        - 'traefik'