version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.heimdall.entrypoints=web, websecure"
      - "traefik.http.routers.heimdall.rule=Host(`pihole.neptune.local`)"
      - "traefik.http.routers.heimdall.tls=true"
      - "traefik.http.routers.heimdall.tls.certresolver=staging"
    ports:
      - "800:80"
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
    environment:
      TZ: 'America/Chicago'
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped
