---
- name: Configuration of rasbperry pi
  hosts: server
  become: true

  pre_tasks:
    - name: Load configuration
      ansible.builtin.include_vars: "{{ item }}"
      loop:
        - config.yml

    - name: Ensure apt cache is up to date.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

  tasks:
    - name: Setup Docker.
      ansible.builtin.import_tasks: tasks/docker/main.yml

    - name: Setup Smb Server.
      ansible.builtin.import_tasks: tasks/smb_server/main.yml
